// Print Hello World......
//   Addtwonumbers/binary numbers/characters.......
//   Calculate compound interest...
//   Calculate power of a number...
//   Swaptwonumbers.....
//   Calculate area of rectangle.....

#include<iostream>
using namespace std;
int main()
{
    cout<<"Hello world";
}
